version: "3.9"
services:
  web:
    image: flask-blog:latest
    ports:
      - "8080:80"  # Mappe le port 80 du conteneur au port 8080 de l'hôte
    volumes:
      - ./blog_project:/app
      - ./blog_project/blog/blog.db:/app/blog.db
